#!/bin/sh
# Install Go dependencies.
# Usage: script/bootstrap

set -e

go get -d -t ./...
go get -v \
    github.com/golang/lint/golint \
    github.com/jteeuwen/go-bindata/... \
    github.com/mitchellh/gox \
    github.com/mlafeldt/pkgcloud/... \
    golang.org/x/tools/cmd/cover
