#!/bin/sh
# Download and install Go dependencies.
# Usage: script/bootstrap

exec go get -v -t \
    ./... \
    github.com/golang/lint/golint \
    github.com/mitchellh/gox \
    golang.org/x/tools/cmd/cover
