#!/bin/sh
# Build project for multiple architectures. With --release, also create
# download archives.
# Usage: script/build [-r|--release]

set -e

git_version=$(git describe --tags --match "v[0-9]*" --abbrev=4 --dirty 2>/dev/null)
version=$(expr "$git_version" : v*'\(.*\)' | sed -e 's/-/./g')
build_dir="build/$version"

echo "Building chef-runner $git_version ..."

echo "Installing dependencies..."
go get -v -t ./...

echo "Running all tests..."
go test -race ./...

echo "Running style checks..."
script/lint

echo "Cross-compiling binaries..."
rm -rf "$build_dir"
gox \
    -output="${build_dir}/{{.Dir}}_${version}_{{.OS}}_{{.Arch}}/{{.Dir}}" \
    -os="darwin linux freebsd openbsd" \
    -ldflags "-X main.GitVersion $git_version" \
    ./...

case "$1" in
-r|--release)
    echo "Creating zip archives..."
    cd "$build_dir"
    for i in *; do zip -r "$i.zip" "$i"; done
    echo "Creating SHA256SUMS file..."
    shasum -a256 *.zip > SHA256SUMS
esac

echo "Done."
