#!/bin/sh
# Generate code coverage statistics for Go packages. With --html, also create
# HTML report and open it in browser.
# Usage: script/coverage [--html]
#
# Works around the fact that `go test -coverprofile` currently does not work
# with multiple packages, see https://code.google.com/p/go/issues/detail?id=6909

set -e

workdir=.cover
profile="$workdir/cover.out"
mode=count

generate_cover_data() {
    rm -rf "$workdir"
    mkdir "$workdir"

    for pkg in "$@"; do
        f="$workdir/$(echo $pkg | tr / -).cover"
        go test -covermode="$mode" -coverprofile="$f" "$pkg"
    done

    echo "mode: $mode" >"$profile"
    grep -h -v "^mode:" "$workdir"/*.cover >>"$profile"
}

show_cover_report() {
    go tool cover -${1}="$profile"
}

packages=$(go list ./...)
generate_cover_data $packages
show_cover_report func
if test "$1" = "--html"; then
    show_cover_report html
fi
